server:
  port: 8082

spring:
  config:
    import: classpath:config-server/src/main/resources/application-common.yml

logging:
  level:
    root: info

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: always
  server:
    port: 9091

info:
  app:
    name: Actor Master
    description: Actor Master Application
    version: 1.0.0

resilience4j:
  retry:
    metrics:
      enabled: true
      legacy:
        enabled: true
    instances:
      retryApi:
        max-attempts: 3
        wait-duration: 3s
  circuitbreaker:
    instances:
      CircuitBreakerService:
        automatic-transition-from-open-to-half-open-enabled: true
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: count_based
        wait-duration-in-open-state: 5s
  ratelimiter:
    instances:
      rateLimiterApi:
        allow-health-indicator-to-fail: true
        event-consumer-buffer-size: 50
        limit-for-period: 3
        limit-refresh-period: 60s
        register-health-indicator: true
        subscribe-for-events: true
        timeout-duration: 0s
    metrics:
      enabled: true
  timelimiter:
    instances:
      timeLimiterApi:
        cancel-running-future: true
        timeout-duration: 2s
    metrics:
      enabled: true
